import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Convert Units Conveniently: Ems, Rems, Pixels, Taiwind, Bootstrap, Picas And More - UnitSwitch",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={
          inter.className + " " + "m-2 sm:flex sm:min-h-screen items-center justify-center"
        }
      >
        {children}
      </body>
    </html>
  );
}
