import "@/globals.css";
import { Analytics } from "@vercel/analytics/react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"], display: "swap", weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Convert Units Conveniently: Ems, Rems, Pixels, Taiwind, Bootstrap, Picas And More - UnitSwitch",
  description: "Generated by create next app",
  authors: [{ name: "Jacob Benison", url: "https://jacobbenison.com/" }],
  verification: {
    google: "AJv1LUmIWivHUie7jKJAIWD_12BrKaqi-HkW0IxeRcs",
  }
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={
          inter.className + " " + "m-2 sm:flex sm:min-h-screen items-center justify-center"
        }
      >
        {children}
        <Analytics />
      </body>
    </html>
  );
}
